name: Release Android

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Release Tag (v1.0.0)'
      status:
        required: true
        description: 'Release Status (beta, stable)'

jobs:
  flutter_release:
    name: Run build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from git
        uses: actions/checkout@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get depedencies
        run: flutter pub get
      - name: Clean the project
        run: flutter clean
      - name: Run build android apk
        run: flutter build apk
      - name: Rename the apk
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/Milk.apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/Milk.apk"
          tag: ${{ github.event.inputs.tag }}-${{ github.event.inputs.status }}
        env:
          GITHUB_REPOSITORY: Parumezan/Milk
