name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Release Tag (v1.0.0)'
      status:
        type: choice
        required: true
        description: 'Release Status (stable, beta)'
        options: 
          - stable
          - beta

jobs:
  flutter_release:
    name: Build & Release on Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from git
        uses: actions/checkout@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get depedencies
        run: flutter pub get
      - name: Clean the project
        run: flutter clean
      - name: Run build android apk
        run: flutter build apk
      - name: Rename apk
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/Milk.apk

      - name: Push to Pre-Releases
        if: ${{ github.event.inputs.status == 'beta' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/Milk.apk"
          prerelease: true
          tag: ${{ github.event.inputs.tag }}-${{ github.event.inputs.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Releases
        if: ${{ github.event.inputs.status == 'stable' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/Milk.apk"
          prerelease: false
          tag: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
